imports_granularity = "Module"
group_imports = "StdExternalCrate"
newline_style = "unix"
tab_spaces = 4
match_block_trailing_comma = true
enum_discrim_align_threshold = 40
struct_field_align_threshold = 40

